name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  |
        docker build . --file Dockerfile --tag cv
        docker run cv
        docker cp $(docker ps -l -q):/cv.pdf cv.pdf
    - name: Publish CV
      uses: EndBug/add-and-commit@v7
      with:
        add: cv.pdf
        branch_mode: create
        author_name: Kirill Korolev
        author_email: kakorolev@edu.hse.ru
        branch: cv
        message: 'Uploading new CV'
      
    
    
