name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish CV 
      run:  |
        name="cv"
        docker build . --file Dockerfile --tag $name
        docker run $name
        docker cp $(docker ps -l -q):/$name.pdf $name.pdf
        git checkout -b $name
        git add $name.pdf
        git commit -m "cv"
        git push origin $name
